Spec tests & controllers for User's CRUD actions
ayau8/menternshift-backend pull request #16
Opened 2024-03-13 05:57 UTC by ayau8

In addition to the present User#Show, the spec tests and controllers for INDEX, CREATE, UPDATE and DESTROY actions have been included accordingly

User#Show also has been further updated to retrieve all the User's associated expertises by adding eager loading in the set_user method. In such case, FE doesn't need to make a separate request and when it fetches the specific user, the associated expertise data in a single query will be retrieved at once

2024-03-13 09:06 UTC, srollins01 commented on spec/controllers/Api/v1/users_controller_spec.rb
> +      expect(users.last.expertises.size).to eq(3)
Inconsistent indentation

2024-03-13 09:09 UTC, srollins01 requested changes
Besides a couple styling issues everything looks good.

2024-03-13 09:09 UTC, srollins01 commented on spec/controllers/Api/v1/users_controller_spec.rb
> +    end
Not aligned with line 57.

2024-03-13 09:09 UTC, srollins01 commented on spec/controllers/Api/v1/users_controller_spec.rb
> +      expect(users.last.expertises.size).to eq(3)
Inconsistent indentation

2024-03-13 09:30 UTC, srollins01 approved these changes

2024-03-19 08:48 UTC, achpsident approved these changes
Looks good, but please reset the branch on top of the latest `master` before merging.

2024-03-21 07:29 UTC, merged