Schema draft4
ayau8/menternshift-backend pull request #6
Opened 2024-01-10 08:26 UTC by mnsom

Hi @achpsident and @ayau8 ,

I didn't change any content from the last push which is "Schema draft3", but organized commits.
reference DB URL: https://kitt.lewagon.com/db/117845

Could you please review each commit and give me a feedback?
If you have any questions, please feel free to let me know.

Thank you,
Mana

2024-01-16 06:31 UTC, ayau8 reviewed
Thanks @mnsom, no additional comment from my side

2024-01-17 00:28 UTC, achpsident requested changes
Let me know if you have any questions or disagree about any of the comments.

2024-01-17 00:28 UTC, achpsident commented on db/migrate/20240110025234_add_columns_to_users.rb
> +    add_column :users, :skill, :text, array: true, default: []
Normally columns are singular, but since these are arrays, let's use the plural form (guidances, languages, skills).

2024-01-17 00:28 UTC, achpsident commented on db/migrate/20240110025234_add_columns_to_users.rb
> +    add_column :users, :isAvailable, :string
```suggestion
 add_column :users, :is_available, :string
```
isAvailable is in camel case, let's use snake case.

2024-01-17 00:28 UTC, achpsident commented on db/migrate/20240110032509_create_expertises.rb
> +      t.integer :year_of_experience
```suggestion
      t.integer :years_of_experience
```

2024-01-17 00:28 UTC, achpsident commented on db/migrate/20240110032649_create_projects.rb
> +      t.text :skill, array: true, default: []
```suggestion
      t.text :skills, array: true, default: []
```

2024-01-17 00:28 UTC, achpsident commented on db/migrate/20240110032944_create_project_areas.rb
> +      t.string :proj_man
```suggestion
      t.string :project_manager
```
No need to use an abbreviation here.

2024-01-17 07:47 UTC, mnsom commented
Hi @achpsident , thank you for your feedback. I agree with your suggestions, so I made changes based on your feedback. Could you please take a look again?
Thank you!
Mana

2024-01-19 00:17 UTC, achpsident approved these changes
LGTM

2024-01-19 13:00 UTC, ayau8 approved these changes
No additional comment from my side. Thanks!

2024-01-24 12:42 UTC, merged